name: Deploy Mirzapur Mandal App

on:
  push:
    branches: [ "main" ] # अगर आपकी ब्रांच का नाम master है, तो यहाँ master लिखें

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Insert Secret Link into HTML
        env:
          SECRET_URL: ${{ secrets.Link }}
        run: |
          sed -i "s|\${{ secrets.Link }}|$SECRET_URL|g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
